AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: GHL webhook listener (signature check + Redis allowlist + enqueue)

Parameters:
  DeployEnvironment:
    Type: String
    Default: staging
  FunctionName:
    Type: String
    Default: ghl-webhook-events-staging
  VpcSubnetIds:
    Type: String
  VpcSecurityGroupIds:
    Type: String
  SecretsManagerArn:
    Type: String
    Default: arn:aws:secretsmanager:us-east-2:214046906223:secret:staging-secrets-PT0K6h
  RedisSecretKey:
    Type: String
    Default: REDIS_URL
  AllowlistKey:
    Type: String
    Default: ghl:webhook:allowlist
  QueueName:
    Type: String
    Default: ghl-contact-update
  PublicKeySecretKey:
    Type: String
    Default: GHL_WEBHOOK_PUBLIC_KEY

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 10
    MemorySize: 256
    Tracing: Active

Resources:
  GhlWebhookListenerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref FunctionName
      Handler: handler.handler
      CodeUri: .
      Policies:
        - AWSLambdaVPCAccessExecutionRole
      VpcConfig:
        SecurityGroupIds: !Split [",", !Ref VpcSecurityGroupIds]
        SubnetIds: !Split [",", !Ref VpcSubnetIds]
      Environment:
        Variables:
          REDIS_URL: !Sub "{{resolve:secretsmanager:${SecretsManagerArn}:SecretString:${RedisSecretKey}}}"
          GHL_WEBHOOK_ALLOWLIST_KEY: !Ref AllowlistKey
          GHL_WEBHOOK_QUEUE_NAME: !Ref QueueName
          GHL_WEBHOOK_PUBLIC_KEY: !Sub "{{resolve:secretsmanager:${SecretsManagerArn}:SecretString:${PublicKeySecretKey}}}"
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: false
        EntryPoints:
          - src/handler.ts

Outputs:
  GhlWebhookListenerArn:
    Description: GHL webhook listener Lambda ARN
    Value: !GetAtt GhlWebhookListenerFunction.Arn
